/**
 * Manual mappings for AWS Overview category topics that do not exactly match IAM service names.
 */
export const topicAliases: Record<string, string[]> = {
  amazonemr: ['elasticmapreduce', 'emr-containers', 'emr-serverless'],
  amazonkinesis: ['kinesis', 'kinesisanalytics', 'kinesisvideo', 'firehose'],
  amazondatafirehose: ['firehose'],
  amazonmanagedserviceforapacheflink: ['kinesisanalytics'],
  quick: ['quicksight'],
  amazonmanagedstreamingforapachekafka: ['kafka', 'kafkaconnect'],
  amazonmanagedworkflowsforapacheairflow: ['airflow', 'airflow-serverless'],
  amazonsimplenotificationservice: ['sns'],
  amazonsimplequeueservice: ['sqs'],
  amazonchimesdk: ['chime'],
  connectcustomer: ['profile'],
  amazonses: ['ses'],
  awscostexplorer: ['ce'],
  awsbudgets: ['budgets'],
  savingsplans: ['savingsplans'],
  amazonrelationaldatabaseservice: ['rds', 'rds-data', 'rds-db'],
  amazonrdsfordb2: ['rds'],
  amazonrdsonvmware: ['rds'],
  amazonrelationaldatabaseserviceforvmware: ['rds'],
  amazonaurora: ['rds', 'dsql'],
  amazondocumentdb: ['docdb-elastic'],
  amazonlightsailmanageddatabases: ['lightsail'],
  amazonworkspacesapplications: ['appstream'],
  amazonworkspacescore: ['workspaces'],
  amazonworkspacesweb: ['workspaces-web'],
  amazonlocationservice: ['geo', 'geo-maps', 'geo-places', 'geo-routes'],
  awsiotbutton: ['iot'],
  awsiotcore: ['iot', 'iotdeviceadvisor'],
  awsiotdevicedefender: ['iot'],
  awsiotdevicemanagement: ['iot', 'iotfleethub'],
  awsiotexpresslink: ['iot'],
  awsiotgreengrass: ['greengrass'],
  awspartnerdevicecatalog: ['iot'],
  freertos: ['freertos'],
  amazonaugmentedai: ['sagemaker'],
  amazonlex: ['lex'],
  amazonpartyrock: ['bedrock'],
  amazonsagemakerai: ['sagemaker', 'sagemaker-geospatial', 'sagemaker-mlflow'],
  awscloudformation: ['cloudformation'],
  awsconsolemobileapplication: ['consoleapp'],
  awshealth: ['health'],
  opsworks: ['opsworks', 'opsworks-cm'],
  amazonqdeveloperinchatapplications: ['chatbot'],
  awstransformmgn: ['transform'],
  awssnowfamily: ['snowball', 'snow-device-management'],
  directconnect: ['directconnect'],
  elasticloadbalancing: ['elasticloadbalancing'],
  awsprivate5g: ['private-networks'],
  awstransitgateway: ['ec2'],
  amazonvpc: ['ec2'],
  sitetositevpn: ['ec2'],
  amazoncognito: ['cognito-idp', 'cognito-identity', 'cognito-sync'],
  awsidentityandaccessmanagement: ['iam'],
  awsresourceaccessmanager: ['ram'],
  awssecurityhubcspm: ['securityhub'],
  awswafcaptcha: ['wafv2'],
  amazonfilecache: ['fsx'],
  amazonfsxforlustre: ['fsx'],
  amazonfsxfornetappontap: ['fsx'],
  amazonfsxforopenzfs: ['fsx'],
  amazonfsxforwindowsfileserver: ['fsx'],
  amazonsimplestorageservice: ['s3', 's3express', 's3-object-lambda', 's3-outposts']
}

/**
 * AWS Overview topics that are navigation/comparison content or products without IAM actions.
 */
export const topicSkips = new Set<string>([
  'compareawscomputeservices',
  'amazonlinux2023',
  'awsfargate',
  'awswavelength',
  'vmwarecloudonaws',
  'reservedinstancereporting',
  'redhatopenshiftserviceonaws',
  'compareawsdatabaseservices',
  'awsdeepcomposer',
  'awsdeepracer',
  'kiro',
  'integratedprivatewirelessonaws'
])

/**
 * Explicit category assignment for IAM service prefixes that are absent from AWS Overview or need a forced category.
 */
export const serviceCategoryOverrides: Record<string, string> = {
  a4b: 'business-applications',
  'access-analyzer': 'security-identity-and-compliance',
  account: 'management-and-governance',
  'account-access': 'security-identity-and-compliance',
  'acm-pca': 'security-identity-and-compliance',
  'aco-automation': 'compute',
  'action-recommendations': 'management-and-governance',
  activate: 'compute',
  'agentaccess-mcp': 'end-user-computing',
  'agent-registry': 'machine-learning-and-ai',
  aidevops: 'machine-learning-and-ai',
  aiops: 'machine-learning-and-ai',
  amplifybackend: 'front-end-web-and-mobile',
  amplifyuibuilder: 'front-end-web-and-mobile',
  apigateway: 'networking-and-content-delivery',
  'app-integrations': 'application-integration',
  appconfig: 'management-and-governance',
  'application-autoscaling': 'management-and-governance',
  'application-signals': 'management-and-governance',
  'application-signals-mcp': 'management-and-governance',
  'application-transformation': 'migration-and-transfer',
  applicationinsights: 'management-and-governance',
  'appmesh-preview': 'networking-and-content-delivery',
  appstudio: 'business-applications',
  apptest: 'migration-and-transfer',
  'arc-region-switch': 'management-and-governance',
  'arc-zonal-shift': 'management-and-governance',
  arsenal: 'migration-and-transfer',
  'aws-external-anthropic': 'machine-learning-and-ai',
  'aws-marketplace': 'cloud-financial-management',
  'aws-marketplace-management': 'cloud-financial-management',
  'aws-portal': 'cloud-financial-management',
  awsconnector: 'business-applications',
  'backup-gateway': 'storage',
  'backup-search': 'storage',
  'backup-storage': 'storage',
  'bcm-dashboards': 'cloud-financial-management',
  'bcm-data-exports': 'cloud-financial-management',
  'bcm-pricing-calculator': 'cloud-financial-management',
  'bcm-recommended-actions': 'cloud-financial-management',
  'bedrock-agentcore': 'machine-learning-and-ai',
  'bedrock-mantle': 'machine-learning-and-ai',
  'bedrock-websearch': 'machine-learning-and-ai',
  billing: 'cloud-financial-management',
  bugbust: 'developer-tools',
  cases: 'business-applications',
  'cleanrooms-ml': 'machine-learning-and-ai',
  clouddirectory: 'security-identity-and-compliance',
  'cloudfront-keyvaluestore': 'networking-and-content-delivery',
  'cloudtrail-data': 'management-and-governance',
  codeconnections: 'developer-tools',
  'codedeploy-commands-secure': 'developer-tools',
  'codeguru-profiler': 'developer-tools',
  'codeguru-reviewer': 'developer-tools',
  'codeguru-security': 'security-identity-and-compliance',
  codestar: 'developer-tools',
  'codestar-connections': 'developer-tools',
  'codestar-notifications': 'management-and-governance',
  codewhisperer: 'machine-learning-and-ai',
  connect: 'business-applications',
  'connect-campaigns': 'business-applications',
  consolidatedbilling: 'cloud-financial-management',
  controlcatalog: 'management-and-governance',
  'cost-optimization-hub': 'cloud-financial-management',
  'customer-verification': 'business-applications',
  databrew: 'analytics',
  dax: 'analytics',
  dbqms: 'developer-tools',
  deadline: 'media',
  dlm: 'storage',
  'ds-data': 'security-identity-and-compliance',
  ec2: 'compute',
  'ec2-instance-connect': 'compute',
  ec2messages: 'compute',
  'ecr-public': 'containers',
  'ecs-mcp': 'containers',
  'eks-auth': 'containers',
  'eks-mcp': 'containers',
  'elemental-activations': 'media',
  'elemental-inference': 'media',
  'elemental-support-cases': 'business-applications',
  'elemental-support-content': 'media',
  evidently: 'management-and-governance',
  eventsbilltoaws: 'cloud-financial-management',
  evs: 'compute',
  'finops-agent': 'cloud-financial-management',
  'finspace-api': 'analytics',
  freetier: 'cloud-financial-management',
  gameliftstreams: 'game-tech',
  glacier: 'storage',
  groundtruthlabeling: 'machine-learning-and-ai',
  'health-agent': 'business-applications',
  honeycode: 'business-applications',
  'identity-sync': 'security-identity-and-compliance',
  identitystore: 'security-identity-and-compliance',
  'identitystore-auth': 'security-identity-and-compliance',
  importexport: 'storage',
  'inspector-scan': 'security-identity-and-compliance',
  inspector2: 'security-identity-and-compliance',
  'inspector2-telemetry': 'security-identity-and-compliance',
  interconnect: 'networking-and-content-delivery',
  internetmonitor: 'networking-and-content-delivery',
  invoicing: 'cloud-financial-management',
  'iot-device-tester': 'internet-of-things',
  iotjobsdata: 'internet-of-things',
  iotmanagedintegrations: 'internet-of-things',
  iotwireless: 'internet-of-things',
  iq: 'management-and-governance',
  'iq-permission': 'management-and-governance',
  ivschat: 'media',
  'kafka-cluster': 'analytics',
  'kendra-ranking': 'machine-learning-and-ai',
  'license-manager-linux-subscriptions': 'management-and-governance',
  'license-manager-user-subscriptions': 'management-and-governance',
  lightsail: 'compute',
  logs: 'management-and-governance',
  machinelearning: 'machine-learning-and-ai',
  'managedblockchain-query': 'blockchain',
  mapcredits: 'cloud-financial-management',
  marketplacecommerceanalytics: 'cloud-financial-management',
  mechanicalturk: 'business-applications',
  mediaimport: 'media',
  'mediapackage-vod': 'media',
  mediapackagev2: 'media',
  'medical-imaging': 'machine-learning-and-ai',
  mgn: 'migration-and-transfer',
  'migrationhub-orchestrator': 'migration-and-transfer',
  'migrationhub-strategy': 'migration-and-transfer',
  mobileanalytics: 'front-end-web-and-mobile',
  mpa: 'security-identity-and-compliance',
  'neptune-graph': 'analytics',
  'network-security-director': 'security-identity-and-compliance',
  'network-security-manager': 'security-identity-and-compliance',
  networkflowmonitor: 'networking-and-content-delivery',
  networkmanager: 'networking-and-content-delivery',
  'networkmanager-chat': 'networking-and-content-delivery',
  networkmonitor: 'networking-and-content-delivery',
  'notifications-contacts': 'management-and-governance',
  'nova-act': 'machine-learning-and-ai',
  oam: 'management-and-governance',
  observabilityadmin: 'management-and-governance',
  odb: 'analytics',
  omics: 'machine-learning-and-ai',
  one: 'business-applications',
  opensearch: 'analytics',
  osis: 'analytics',
  partnercentral: 'management-and-governance',
  'partnercentral-account-management': 'management-and-governance',
  'payment-cryptography': 'cloud-financial-management',
  payments: 'cloud-financial-management',
  'pca-connector-ad': 'security-identity-and-compliance',
  'pca-connector-scep': 'security-identity-and-compliance',
  pcs: 'compute',
  pi: 'management-and-governance',
  pipes: 'application-integration',
  pricing: 'cloud-financial-management',
  pricingplanmanager: 'cloud-financial-management',
  'purchase-orders': 'cloud-financial-management',
  qapps: 'machine-learning-and-ai',
  qbusiness: 'machine-learning-and-ai',
  qldb: 'blockchain',
  rbin: 'management-and-governance',
  'redshift-data': 'analytics',
  'refactor-spaces': 'migration-and-transfer',
  researchstudio: 'machine-learning-and-ai',
  resiliencehub: 'management-and-governance',
  'resource-explorer': 'management-and-governance',
  'resource-explorer-2': 'management-and-governance',
  'resource-groups': 'management-and-governance',
  rhelkb: 'customer-enablement',
  robomaker: 'management-and-governance',
  rolesanywhere: 'security-identity-and-compliance',
  'route53-recovery-cluster': 'networking-and-content-delivery',
  'route53-recovery-control-config': 'networking-and-content-delivery',
  'route53-recovery-readiness': 'networking-and-content-delivery',
  route53domains: 'networking-and-content-delivery',
  route53globalresolver: 'networking-and-content-delivery',
  route53profiles: 'networking-and-content-delivery',
  route53resolver: 'networking-and-content-delivery',
  rtbfabric: 'management-and-governance',
  rum: 'management-and-governance',
  s3files: 'storage',
  s3tables: 'storage',
  s3vectors: 'storage',
  'sagemaker-data-science-assistant': 'machine-learning-and-ai',
  'sagemaker-unified-studio-mcp': 'machine-learning-and-ai',
  scheduler: 'application-integration',
  schemas: 'application-integration',
  scn: 'business-applications',
  sdb: 'analytics',
  'security-ir': 'security-identity-and-compliance',
  securityagent: 'security-identity-and-compliance',
  serviceextract: 'migration-and-transfer',
  servicequotas: 'management-and-governance',
  signer: 'security-identity-and-compliance',
  signin: 'security-identity-and-compliance',
  simspaceweaver: 'compute',
  sms: 'migration-and-transfer',
  'sms-voice': 'business-applications',
  'social-messaging': 'business-applications',
  sqlworkbench: 'developer-tools',
  'ssm-contacts': 'management-and-governance',
  'ssm-guiconnect': 'management-and-governance',
  'ssm-incidents': 'management-and-governance',
  'ssm-quicksetup': 'management-and-governance',
  'ssm-sap': 'management-and-governance',
  ssmmessages: 'management-and-governance',
  'sso-directory': 'security-identity-and-compliance',
  'sso-oauth': 'security-identity-and-compliance',
  sts: 'security-identity-and-compliance',
  support: 'management-and-governance',
  supportauthz: 'management-and-governance',
  'support-console': 'management-and-governance',
  supportapp: 'management-and-governance',
  supportplans: 'management-and-governance',
  sustainability: 'management-and-governance',
  synthetics: 'management-and-governance',
  tag: 'management-and-governance',
  tax: 'cloud-financial-management',
  'timestream-influxdb': 'analytics',
  tiros: 'machine-learning-and-ai',
  tnb: 'networking-and-content-delivery',
  'transform-custom': 'migration-and-transfer',
  ts: 'developer-tools',
  'user-subscriptions': 'management-and-governance',
  uxc: 'front-end-web-and-mobile',
  'vendor-insights': 'cloud-financial-management',
  voiceid: 'business-applications',
  'vpc-lattice-svcs': 'networking-and-content-delivery',
  'waf-regional': 'security-identity-and-compliance',
  wam: 'end-user-computing',
  wickr: 'business-applications',
  wisdom: 'business-applications',
  worklink: 'end-user-computing',
  workmailmessageflow: 'business-applications',
  'workspaces-instances': 'end-user-computing'
}
